@base_address = http://localhost:5151/api/authentication

###
POST {{base_address}}/register-user
Content-Type: application/json

{
  "username": "Adminanthony",
  "email": "admin@b.c",
  "role" : "Admin"
}

###
POST {{base_address}}/login-user
Content-Type: application/json

{
  "email": "admin@b.c",

}

### 
POST {{base_address}}/refresh-token
Content-Type: application/json

{
  "token":"",
   "refreshToken": ""
}


