@base_address = http://localhost:5151/api/authentication

###
# GET {{base_address}}

###
POST {{base_address}}/register-user
Content-Type: application/json

{
  "username": "Anthony",
  "email": "a@b.c",

}

###
POST {{base_address}}/login-user
Content-Type: application/json

{
  "email": "a@b.c",


}


