@base_address = http://localhost:5151/api/People
@base_token =
###
GET {{base_address}}
Authorization: Bearer {{base_token}}


###
POST {{base_address}}
Content-Type: application/json

{
  "firstName": "Immaculate joe",
  "lastName": "Doe"
}


###
GET {{base_address}}/1

###
PUT {{base_address}}/1
Content-Type: application/json
Authorization: Bearer {{base_token}}

{
  "id": 1,
  "firstName": "Immaculate",
  "lastName": "Doe"
}

###
DELETE {{base_address}}/1
